<?php

namespace Canducci\ReCaptcha;

abstract class ReCaptchaScriptLanguage
{
    const Arabic = "ar";
    const Afrikaans = "af";
    const Amharic = "am";
    const Armenian = "hy";
    const Azerbaijani = "az";
    const Basque = "eu";
    const Bengali = "bn";
    const Bulgarian = "bg";
    const Catalan = "ca";
    const Chinese_Hong_Kong = "zh-HK";
    const Chinese_Simplified = "zh-CN";
    const Chinese_Traditional = "zh-TW";
    const Croatian = "hr";
    const Czech = "cs";
    const Danish = "da";
    const None = "";
    const Dutch = "nl";
    const English_UK = "en - GB";
    const English_US = "en";
    const Estonian = "et";
    const Filipino = "fil";
    const Finnish = "fi";
    const French = "fr";
    const French_Canadian = "fr-CA";
    const Galician = "gl";
    const Georgian = "ka";
    const German = "de";
    const German_Austria = "de-AT";
    const German_Switzerland = "de-CH";
    const Greek = "el";
    const Gujarati = "gu";
    const Hebrew = "iw";
    const Hindi = "hi";
    const Hungarain = "hu";
    const Icelandic = " is";
    const Indonesian = "id";
    const Italian = "it";
    const Japanese = "ja";
    const Kannada = "kn";
    const Korean = "ko";
    const Laothian = "lo";
    const Latvian = "lv";
    const Lithuanian = "lt";
    const Malay = "ms";
    const Malayalam = "ml";
    const Marathi = "mr";
    const Mongolian = "mn";
    const Norwegian = "no";
    const Persian = "fa";
    const Polish = "pl";
    const Portuguese = "pt";
    const Portuguese_Brazil = "pt-BR";
    const Portuguese_Portugal = "pt-PT";
    const Romanian = "ro";
    const Russian = "ru";
    const Serbian = "sr";
    const Sinhalese = "si";
    const Slovak = "sk";
    const Slovenian = "sl";
    const Spanish = "es";
    const Spanish_Latin_America = "es-419";
    const Swahili = "sw";
    const Swedish = "sv";
    const Tamil = "ta";
    const Telugu = "te";
    const Thai = "th";
    const Turkish = "tr";
    const Ukrainian = "uk";
    const Urdu = "ur";
    const Vietnamese = "vi";
    const Zulu = "zu";
}